### ISSUE TITLE
Console attachment logic

### ISSUE THREAD

**Issue by ctrueden** [apposed/jaunch#30]
The ImageJ Launcher has logic to attach to a console using `freopen` with channels `CONIN$` (stdin) and `CONOUT$` (stdout and stderr), as well as create a new console using `FreeConsole()` + `AllocConsole()`. And it has a hidden option `--console`/`--attach-console` which calls `attach_win_console()` to do this. It also has `--new-console` to create a new console. Is this ever actually necessary?

**Comment by ctrueden** [comment]
What we really need though is to attach contingently to the console, depending on whether one is already active. And only pop a *new* console when `--new-console` is given as a command line argument.

**Comment by hinerm** [comment]
Just noting that in https://github.com/apposed/jaunch/commit/392c60e690fa19c4c12b9003696ad334fbad4dec I set `-mwindows` to disable the console. That may need to be reverted to attach to an existing console. Then just always try `AttachConsole` and if it fails, contingently create a new one as suggested.

If we do go back to console mode I'm curious, if the `AttachConsole` fails, if it will still make/show a new console. If so it looks like we can hide it (if `--new-console` is not present) with
```c
// Get the handle to the console window
HWND consoleWindow = GetConsoleWindow();
    
// Check if the console window handle is valid
if (consoleWindow != NULL) {
    // Hide the console window
    ShowWindow(consoleWindow, SW_HIDE);
}
```

**Comment by hinerm** [comment]
>That may need to be reverted to attach to an existing console.

Actually right now when I launch from an existing console Fiji just attaches to it. I'm actually not sure we need any other logic here at all.

**Comment by hinerm** [comment]
Since the `ctrl + c` is not Jaunch specific and covered in https://github.com/fiji/fiji/issues/347, and OS focus is also a separate issue covered in https://github.com/apposed/jaunch/issues/52 I think think the actual console attachment logic is working as desired and closing this issue. We can create a new one if behavior needs to be modified specifically with respect to console attachment.

**Comment by hinerm** [comment]
[It was noted](https://imagesc.zulipchat.com/#narrow/channel/327238-Fiji/topic/Can.20no.20longer.20start.20jaunch.20with.20windows.2011/near/487210423) that with https://github.com/apposed/jaunch/commit/392c60e690fa19c4c12b9003696ad334fbad4dec, jaunch applications simply fail to launch on Windows powershell.

They continue to work in `mingw` from the [git for windows](https://gitforwindows.org/) bundle. But it seems that more care will need to be taken in creating/attaching a console.

Note that the console issues are related to [focus aquisition](https://github.com/apposed/jaunch/issues/52) and may need to be solved with consideration for each other.

Also, for reference, the `ctrl + c` failure is being addressed in https://github.com/fiji/fiji/issues/375

**Comment by ctrueden** [comment]
@hinerm If we have to, we could build two different windows executables, similar to how there was java.exe and javaw.exe for many years. (Do Windows OpenJDKs still ship with a javaw.exe? If not: you could examine the OpenJDK java launcher's source code to see how they avoid the need for it.)

**Comment by ctrueden** [comment]
I made some progress (on a branch called `console-playground` as of this writing). Here is what I learned:

* The `file` command, available from Git Bash, identifies whether a given EXE file is a GUI one or a console one.
* The Jaunch C launcher executable is compiled in GUI mode, due to the `-mwindows` flag in `bin/compile-launcher.sh`.
* The Jaunch Kotlin configurator executable is compiled in console mode, because it's what Gradle+Kotlin is doing. :shrug: 
* The launcher, when invoking the configurator via `CreateProcess`, was passing `0` for the flags, but we should be passing `CREATE_NO_WINDOW` to avoid spawning a console window for the subprocess. That change is done on the aforementioned branch.
* A Windows program compiled in GUI mode does not attach to the calling process's console by default; you have to do it using [`AttachConsole`](https://learn.microsoft.com/en-us/windows/console/attachconsole); the aforementioned branch is doing this as well, [as did the ImageJ launcher](https://github.com/imagej/imagej-launcher/blob/04aeccd4cdb0648f642bda9e7edff42627541920/src/main/c/platform.c#L754-L785).

Unfortunately, even with `AttachConsole`—and even if we go further and use `freopen` to reopen the stdin/stdout/stderr (not sure whether doing this even makes a difference...)—the invoked launcher is still in a bad state because the calling process i.e. the shell (CMD or PS) is set to receive input along with the launcher, because on Windows, consoles can have multiple processes attached to them and "there is no guarantee that input is received by the process for which it was intended" ([source](https://learn.microsoft.com/en-us/windows/console/creation-of-a-console)) which seems insane to me. In effect what happens is if you launch e.g. Jy for the Jython REPL, and then start typing commands, only *some* of the keystrokes go to Jython, while others go to the containing shell, resulting in a total mess.

There are a few different ways to mitigate this horror:
* Use a simple batch wrapper script with a single line like `@"%~dp0jy-windows-x64.exe" %*`, and use that batch file to launch on the console. (Thanks to [this blog post](https://lastpixel.tv/win32-application-as-both-gui-and-console/) for the tip!)
* OR: when running from CMD, use `start /wait jy-windows-x64.exe`.
* OR: when running from PS, use `Start-Process -Wait .\jy-windows-x64.exe`.
* OR: compile the Jaunch native launcher as a console app rather than a GUI one by removing the `-mwindows` flag from the `bin\compile-launcher.sh` script. The downside of using a console app is that a *new* console will pop up when launching the program from outside a console e.g. when double-clicking it from File Explorer.

Those first three options all work with the launcher compiled as a GUI app, but only if we `AttachConsole` to the parent process's console as done on the `console-playground` branch; otherwise, the program shuts down right quick without ever emitting any visible output.

I double checked the status of `java.exe`/`javaw.exe` for OpenJDK, and `python.exe`/`pythonw.exe` for Python, and both technologies still ship these dual executables so that callers can choose whether to operate their programs in GUI mode or in console mode. So the most surefire solution for Jaunch consumers would be for us to do the same, compiling Windows executables in both GUI and console modes, so that Jaunch-based programs can then offer both flavors to their users, with instructions for people to use the console one when running from the console, and the GUI one otherwise. :shrug: 

That said, I'm tempted to keep this `console-playground` approach, except only do the `AttachConsole` thing if the `--console` flag is given, like how the ImageJ launcher works... but then also keep the .bat file and have it pass `--console`, as well as auto-detect the arch suffix so that we only need one .bat file for both executables. Something like this:
```batch
@echo off
if "%PROCESSOR_ARCHITECTURE%" == "AMD64" (
    @"%~dp0fiji-windows-x64.exe" --console %*
) else if "%PROCESSOR_ARCHITECTURE%" == "ARM64" (
    @"%~dp0fiji-windows-arm64.exe" --console %*
) else (
    echo Unsupported CPU architecture: %PROCESSOR_ARCHITECTURE%
    exit /b 1
)
```

The big advantage of such a shenanigan is that we'd avoid the crazy mixed up behavior of multiple processes connected to one console, in the case that someone naively runs `.\fiji-windows-x64.exe` from a PowerShell or whatnot (they'd just get another prompt coming back immediately, and a Fiji main window popping up like usual), but if they run `.\fiji.bat` it would still do the right thing.

@hinerm What do you think? I know I wrote a lot above, but the decision is really:

A) Ship two exes per platform: e.g. `fiji-windows-x64.exe` (GUI mode) and `fiji-windows-x64-console.exe` (console mode)
or
B) Ship only one exe compiled in GUI mode, along with a `fiji.bat` for proper use from the console.

I doubt there is a better solution, or the OpenJDK and/or Python projects would be using it instead of the dual exes.

**Comment by ctrueden** [comment]
I polished up the `console-playground` branch and merged it. This issue is now 90+% resolved. The only thing I still want to do, before calling it good enough, is to see if we can obtain the name of the parent process, and then issue a warning continent on whether we're in the *bad situation*: a GUI app launched from a console shell without using wait mode nor wrapped in a batch file.

Claude AI spit out the following code that as usual might be nonsense or might be a useful starting point:
```c
#include <tlhelp32.h>
...
static BOOL isLaunchedFromExplorer() {
    // Get parent process ID
    DWORD parentPID;
    HANDLE snapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
    if (snapshot == INVALID_HANDLE_VALUE) return FALSE;

    DWORD currentPID = GetCurrentProcessId();
    PROCESSENTRY32W pe32;
    pe32.dwSize = sizeof(pe32);

    if (!Process32FirstW(snapshot, &pe32)) {
        CloseHandle(snapshot);
        return FALSE;
    }

    parentPID = 0;
    do {
        if (pe32.th32ProcessID == currentPID) {
            parentPID = pe32.th32ParentProcessID;
            break;
        }
    } while (Process32NextW(snapshot, &pe32));

    CloseHandle(snapshot);

    // Get parent process name
    snapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
    if (snapshot == INVALID_HANDLE_VALUE) return FALSE;

    pe32.dwSize = sizeof(pe32);
    if (!Process32FirstW(snapshot, &pe32)) {
        CloseHandle(snapshot);
        return FALSE;
    }

    BOOL fromExplorer = FALSE;
    do {
        if (pe32.th32ProcessID == parentPID) {
            fromExplorer = _wcsicmp(pe32.szExeFile, L"explorer.exe") == 0;
            break;
        }
    } while (Process32NextW(snapshot, &pe32));

    CloseHandle(snapshot);
    return fromExplorer;
}
```

**Comment by ctrueden** [comment]
With 749bc509854014f5a77eda3b67e6451b6ce2e85f, I now consider this issue to be fully resolved! :tada: Note that there are no command line flags `--console`, `--attach-console`, `--new-console`... but I do not believe we need them as things stand. They can still be added if it turns out to be necessary to offer manual control of Windows console behavior.
