### ISSUE TITLE
Fiji launcher doesn't apply updates

### ISSUE THREAD

**Issue by hinerm** [apposed/jaunch#41]
If there is a pending update, launching Fiji with the Jaunch launcher doesn't seem to apply it (the `update` folder remains, as seen below). 

![image](https://github.com/apposed/jaunch/assets/1123809/ea5b583c-456f-455e-b084-f160fdff7adf)

This prevents the updater from running.

![image](https://github.com/apposed/jaunch/assets/1123809/f3a0428e-33fe-489d-b291-f02976bc1882)

**Comment by ctrueden** [comment]
Duplicate of #3.
