### ISSUE TITLE
Initial focus is set on text entry component

### ISSUE THREAD

**Issue by hinerm** [apposed/jaunch#45]
When launching Fiji with Jaunch, focus is initially set on the search bar.

With `fiji-windows-x64.exe`:
![image](https://github.com/apposed/jaunch/assets/1123809/e8b9dbcd-b8dc-4c1b-ac0e-3e2b4126acdf)

With `ImageJ-win64.exe`
![image](https://github.com/apposed/jaunch/assets/1123809/4497b107-3a0f-42e7-844f-8641c30073ef)

This is a minor annoyance but a change in behavior, and will surprise people who are used to opening things with shortcuts after starting Fiji.

**Comment by ctrueden** [comment]
I tracked down the problem to the inclusion of the `-Dimagej.splash=true` flag. As a workaround, you can comment out this flag from your `fiji.toml`. We will need to dig into the `net.imagej.launcher.SplashScreen` class in imagej-launcher in order to fix this properly.

**Comment by hinerm** [comment]
So I tried a simple patch:

```diff
--- a/src/main/java/net/imagej/launcher/SplashScreen.java
+++ b/src/main/java/net/imagej/launcher/SplashScreen.java
@@ -110,6 +110,7 @@ public class SplashScreen {
                                        for (final Window win : windows) {
                                                if (win.isVisible() && win != splashWindow) {
                                                        hide();
+                                                       win.requestFocus();
                                                        return;
                                                }
                                        }
```

and interestingly this does change the focus to the main Fiji window, so that the search box doesn't get focus, but the _operating system focus_ never goes to Fiji.. so you have to manually click on the Fiji window.

Interestingly, this seems to be how the old launcher behaves from the command prompt (but not double-clicking the executable).

If we can fix this for clicking the `exe` it would be nice if it also worked from the command prompt.

I have tried combinations of the following with no luck yet:
```java
EventQueue.invokeLater(
	new Runnable() {
		@Override
		public void run() {
			win.setFocusableWindowState(true);
			win.toFront();
			win.requestFocus();
			win.setAlwaysOnTop(true);
		}
	});
```

**Comment by hinerm** [comment]
Hmmm. so a console window still flashes briefly when launching with Jaunch. I tried variations of `linkerOpts = mutableListOf("-Wl,--subsystem,windows")` for the configurator and launcher (instead of just the shortcut `-mwindows`) with no change.

FWIW it seems that the `win.requestFocus` fix above was sufficient for desired behavior on Linux when launching from the CLI.
