### ISSUE TITLE
faile to build: jaunch.c can't find jni.h

### ISSUE THREAD

**Issue by Kiri2002** [apposed/jaunch#48]
in Archlinux with jdk21-openjdk,
 ```
 ~/Build/jaunch/src/jaunch-main> archlinux-java status                                        05/11/2024 03:18:48 PM PM
Available Java environments:
  java-11-openjdk
  java-17-openjdk
  java-21-openjdk (default)
  java-22-openjdk
  java-8-openjdk
```
 got ```jni.h``` in  ```/usr/lib/jvm/java-21-openjdk/include/jni.h ```
 ```
 ~/Build/jaunch/src/jaunch-main> ls /usr/lib/jvm/java-21-openjdk/include/jni.h              2 05/11/2024 03:17:06 PM PM
╭───┬────────────────────────────────────────────┬──────┬──────────┬─────────────╮
│ # │                    name                    │ type │   size   │  modified   │
├───┼────────────────────────────────────────────┼──────┼──────────┼─────────────┤
│ 0 │ /usr/lib/jvm/java-21-openjdk/include/jni.h │ file │ 74.2 KiB │ 3 weeks ago │
╰───┴────────────────────────────────────────────┴──────┴──────────┴─────────────╯
```
 
 
 
 But I failed to build
 ```
 ~/Build/jaunch/src/jaunch-main> make dist                                                    05/11/2024 03:17:04 PM PM

[compile-launcher]
+ gcc -I/include -I/include/linux -I/include/darwin -I/include/win32 -fPIC -fno-stack-protector src/c/jaunch.c -o build/launcher-linux-x64
In file included from src/c/jaunch.c:70:
src/c/jvm.h:4:10: fatal error: jni.h: No such file or directory
    4 | #include "jni.h"
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:8: compile-launcher] Error 1
```

**Comment by ctrueden** [comment]
Try setting your `JAVA_HOME` environment variable to point to any OpenJDK installation.

**Comment by ctrueden** [comment]
With 036444abf56143f6c6f3f745f486e7db91079a54, the requirement to set `JAVA_HOME` (or otherwise have access to `jni.h` from an OpenJDK installation) is hopefully made more clear by the build script.

**Comment by ctrueden** [comment]
@Kiri2002 If you look in the `bin/compile-launcher.sh` script, you'll see some heuristics for discerning where an OpenJDK installation might reside. It first uses JAVA_HOME if set, then falls back to `update-java-alternatives -l` which I guess is a Debian/Ubuntu thing, then falls back to `/usr/libexec/java_home` which is a macOS thing. If you want to add/recommend an Archlinux fallback also, that would be awesome. :+1:
