### ISSUE TITLE
No matching Java installations found.

### ISSUE THREAD

**Issue by thuzyp** [apposed/jaunch#57]
Hello. I don't know the meaning of this error since I installed Java 23 in my device and set its '/bin' into my path.

**Comment by thuzyp** [comment]
OK, I found the reason in jvm.toml. Thanks.

**Comment by ctrueden** [comment]
@thuzyp Glad you figured it out! In future, passing the `--debug` flag can be very helpful to get lots of information about what Jaunch is doing, which Java installations it's considering, and if they don't match, why not.
