### ISSUE TITLE
Command line flag aliases not working

### ISSUE THREAD

**Issue by hinerm** [apposed/jaunch#62]
When trying to set the max memory at launch, I can use `--heap` but not `--mem` or `--memory` despite [claims](https://github.com/apposed/jaunch/blob/5f573152532946120191c9598de3b0e086b47393/configs/jvm.toml#L28)

**Comment by ctrueden** [comment]
> despite [claims](https://github.com/apposed/jaunch/blob/5f573152532946120191c9598de3b0e086b47393/configs/jvm.toml#L28)

It's because I am a lying liar. :smiling_imp:
