### ISSUE TITLE
Manual heap setting is triplicated

### ISSUE THREAD

**Issue by hinerm** [apposed/jaunch#63]
When I set max memory with `--heap=blah` I noticed that in the actual command (printed via `--debug --dry-run`) I get three copies:
![image](https://github.com/user-attachments/assets/64594830-300f-4a1e-8f13-d5ab6697a77a)

This might be irrelevant if https://github.com/apposed/jaunch/issues/7 is fixed but that feels like papering over a more fundamental issue which I'm wondering may be related to the number of aliases for a setting?

**Comment by ctrueden** [comment]
> I'm wondering may be related to the number of aliases for a setting?

Seems awfully suspiciously coincidental, yeah! So my :moneybag:'s on your theory being correct. :grin:

**Comment by hinerm** [comment]
>Seems awfully suspiciously coincidental, yeah

Maybe not though. I tried adding/subtracting alternatives in the `toml` and still ended up with three copies of the flag. I'll just have to dig deeper!

**Comment by hinerm** [comment]
OK, so the problem is almost certainly that we are adding `JaunchOptions` multiple times.

I noticed that when we are `Parsing supported options...`, settings in `fiji.toml` are *not* added multiple times, but others are (including those in `jvm.toml` like `--heap`).

So the root of the problem is likely in [the recursive reading of includes](https://github.com/apposed/jaunch/blob/1bd093449437dbb283cd093aa12f0b262aaf882a/src/commonMain/kotlin/config.kt#L304-L305).

What we *want* to happen is that we no longer have duplicate `JaunchOptions` and that we use the version of each option from the "most leaf" toml.

**Comment by ctrueden** [comment]
> What we want to happen is that we no longer have duplicate `JaunchOptions`

Just to be clear: I think the way we should achieve this is by *only parsing each toml file once*, as opposed to doing some sort of `JaunchOption` equality testing and/or deduplication.
